tajmoversapp/urls.py
from django.conf.urls.static import static
from django.urls import path

from . import views
from .views import emailView, successView

urlpatterns = [
    path('',views.homepage ,name='homepage'),
    path('about/',views.about ,name='about'),
    path('service/',views.service ,name='service'),
    path('contact/',views.contact ,name='contact'),
    path('email/', emailView, name='email'),
    path('success/', successView, name='success'),
]

tajmoversproject/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from django.urls import include, path

import tajmoversapp.urls

urlpatterns = [
    path('',include (tajmoversapp.urls)),
    path('admin/', admin.site.urls),
]

tajmoversapp/models.py
from django.db import models

# Create your models here.
class Usermails(models.Model):
    subject= models.CharField(max_length=20)
    message =  models.TextField( null=False)
    from_email = models.EmailField(null=False)
    destinations = models.CharField(null=True, max_length=20)

    class Meta:
        ordering = ('-id',)
                                       
    def __str__(self):
        return f'{self.message} from_email'

tajmoversapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . models import Usermails


class ContactForm(forms.ModelForm):

    class Meta:
        model = Usermails
        fields = ['subject','message','from_email']

tajmoversapp/views.py
import datetime

from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import BadHeaderError, send_mail
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.template import RequestContext
from django.urls import reverse, reverse_lazy


from .forms import ContactForm

# Create your views here.

def homepage(request):
    todays_date = datetime.datetime.now()
    return render(request, 'index.html',{'todays_date':todays_date})

def about(request):
    return render(request, 'about.html')

def service(request):
    return render(request, 'service.html')

def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST, request.FILES)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            from_email = form.cleaned_data['from_email']
            try:
                send_mail(subject, message,from_email, ['markmumba01@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Please input correct details as directed')
            return redirect('success')
    return render(request, "contact.html", {'form': form})

def emailView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST, request.FILES)
        if form.is_valid():
            description = form.cleaned_data['description']
            user_name = form.cleaned_data['user_name']
            from_email = form.cleaned_data['from_email']
            subject = form.cleaned_data['subject']
            try:
                send_mail(description, user_name,subject, from_email, ['markmumba01@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Please input correct details as directed')
            return redirect('success')
    return render(request, "contact.html", {'form': form})

def successView(request):
    return HttpResponse('Success! Thank you for your message. We will reply shortly,')

tajmoversapp/templates/contact.html
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% load staticfiles %}

<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Taj Movers Company</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    {% load static %}
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %} ">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %} ">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %} ">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %} ">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %} ">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %} ">
    <link rel="stylesheet" href="{% static 'css/animate.css' %} ">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %} ">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>
<style>
    #id_subject {




        border-radius: 10px;

    }

    #id_message {

        height: 50px;
        border-color: rgb(182, 182, 182);
        border-radius: 10px;
        height: 200px;

    }

    #id_from_email {

        height: 50px;

        border-radius: 10px;

    }

    #id_destinations {
        height: 100px;

        border-radius: 25px;
    }
</style>

<body>
    <header>
        <div class="header-area">
            <div id="sticky-header" class="main-header-area white-bg">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-2 col-lg-2">
                            <div class="logo-img">
                                <a href="{% url 'homepage' %} ">
                                    <!-- <img src="img/logo.png" alt=""> -->
                                    <h3 style="color: #ff5e13;">TAJ MOVERS</h3>
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-7 col-lg-7">
                            <div class="main-menu d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a class="active" href="{% url 'homepage' %} ">Home</a></li>
                                        <li><a href="{% url 'about' %} ">About</a></li>
                                        <li><a href="{% url 'service' %} ">Services</a></li>
                                        <li><a href="{% url 'contact' %} ">Contact</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3">
                            <div class="quote-area">
                                <div style="color:  #ff5e13;" class="Flaticon flaticon-right-arrow">
                                </div>
                                <div class="get-quote d-none d-lg-block">
                                    <a class="boxed-btn" href="{% url 'contact' %} ">Get a quote</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                    <div class="search_input" id="search_input_box">
                        <div class="container ">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

    <!-- ================ contact section start ================= -->
    <section class="contact-section">



        <!-- form ends -->

        <div class="col-lg-3 offset-lg-1">
            <div class="media contact-info">
                <span class="contact-info__icon"><i class="ti-home"></i></span>
                <div class="media-body">
                    <h3>Nairobi, Mombasa R.d.</h3>
                    <p>Pipeline</p>
                </div>
            </div>
            <div class="media contact-info">
                <span class="contact-info__icon"><i class="ti-tablet"></i></span>
                <div class="media-body">
                    <h3>+254 70022 9711</h3>
                    <p>Mon to Fri 8am to 6pm</p>
                </div>
            </div>
            <div class="media contact-info">
                <span class="contact-info__icon"><i class="ti-email"></i></span>
                <div class="media-body">
                    <h3>japhethfriday@gmail.com</h3>
                    <p>Send us your query anytime!</p>
                </div>
            </div>
        </div>
        </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h2 class="contact-title text-center" style="padding-right: 400px;;">Send us a message<br><a
                        style="text-decoration: none; color: white;" href="mailto:markmumba01@gmail.com"
                        target="_top"><img style="width: 30px; height: 30px;"
                            src="https://image.flaticon.com/icons/svg/109/109617.svg" /></a>
                </h2>
            </div>




    </section>
    <!-- ================ contact section end ================= -->


    <!-- location-area-start -->
    <div class="addres-area black-bg section-padding">
        <div class="container">
            <div class="row">
                <div class="col-xl-4 col-md-4">
                    <div class="single-address text-center">
                        <div class="addres-icon">
                            <img src="{% static 'img/icon/1.png' %} " alt="">
                        </div>
                        <h3>Our Location</h3>
                        <p>Nairobi, Kenya<br>
                            <span class="underline-hover"> Mombasa Road</span></p>
                    </div>
                </div>
                <div class="col-xl-4 col-md-4">
                    <div class="single-address text-center">
                        <div class="addres-icon">
                            <img src="{% static 'img/icon/2.png' %} " alt="">
                        </div>
                        <h3>Opening hour</h3>
                        <p>Mon-Fri (9.00-19.00) <br>
                            Sat-Sun <span class="underline-hover">(Closed)</span></p>
                    </div>
                </div>
                <div class="col-xl-4 col-md-4">
                    <div class="single-address text-center">
                        <div class="addres-icon">
                            <img src="{% static 'img/icon/3.png' %} " alt="">
                        </div>
                        <h3>Drop a message</h3>
                        <p>
                            +254 722 9711
                            <br>
                            <img width="20px" height="20px" src="{% static 'img/gmail.png' %} "> :<a
                                style="text-decoration: none; color: #ff5e13;"
                                href="mailto:japhethfriday@gmail.com?Subject=Hello%20again" target="_bottom"><span
                                    class="underline-hover">Mail Us </span></a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- location-area-end -->

    <!-- footer-start -->
    <footer">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="copyright_part_text text-center">
                        <p class="footer-text m-0">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This
                            template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
                                href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
        </footer>
        <!-- footer-end -->

        <!-- JS here -->
        <script rel="stylesheet/" src="{% static 'js/vendor/modernizr-3.5.0.min.js' %} "></script>
        <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %} "></script>
        <script src="{% static 'js/popper.min.js' %} "></script>
        <script src="{% static 'js/bootstrap.min.js' %} "></script>
        <script src="{% static 'js/owl.carousel.min.js' %} "></script>
        <script src="{% static 'js/isotope.pkgd.min.js' %} "></script>
        <script src="{% static 'js/ajax-form.js' %} "></script>
        <script src="{% static 'js/waypoints.min.js' %} "></script>
        <script src="{% static 'js/jquery.counterup.min.js' %} "></script>
        <script src="{% static 'js/imagesloaded.pkgd.min.js' %} "></script>
        <script src="{% static 'js/scrollIt.js' %} "></script>
        <script src="{% static 'js/jquery.scrollUp.min.js' %} "></script>
        <script src="{% static 'js/wow.min.js' %} "></script>
        <script src="{% static 'js/nice-select.min.js' %} "></script>
        <script src="{% static 'js/jquery.slicknav.min.js' %} "></script>
        <script src="{% static 'js/jquery.magnific-popup.min.js' % } "></script>
    <script src="{% static 'js/plugins.js' %} "></script>

        <!--contact js-->
        <script src="{% static 'js/contact.js' %} "></script>
        <script src="{% static 'js/jquery.ajaxchimp.min.js' %} "></script>
        <script src="{% static 'js/jquery.form.js' %} "></script>
        <script src="{% static 'js/jquery.validate.min.js' %} "></script>
        <script src="{% static 'js/mail-script.js' %} "></script>
        <script src="{% static 'js/main.js' %} "></script>

</body>

</html>

tajmoversapp/templates/navbar.html
{% extends "tajtemplates/base.html" %}
{% load bootstrap4 %}
{% load staticfiles %}
{% block content %}
<head>
    <title>Taj Movers</title>
    {{form.media}}
</head>

<body>
    <header>
        <div class="header-area">
            <div id="sticky-header" class="main-header-area white-bg">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-2 col-lg-2">
                            <div class="logo-img">
                                <a href="index.html">
                                    <!-- <img src="img/logo.png" alt=""> -->
                                    <h3 style="color: #ff5e13;">TAJ MOVERS</h3>
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-7 col-lg-7">
                            <div class="main-menu d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a class="active" href="{% url 'homepage' %} ">Home</a></li>
                                        <li><a href="{% url 'about' %} ">About</a></li>
                                        <li><a href="{% url 'service' %} ">Services</a></li>
                                        <li><a href="{% url 'contact' %} ">Contact</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3">
                            <div class="quote-area">
                                <div style="color:  #ff5e13;" class="Flaticon flaticon-right-arrow">                                    
                                </div>
                                <div class="get-quote d-none d-lg-block">
                                    <a class="boxed-btn" href="contact.html">Get a quote</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                    <div class="search_input" id="search_input_box">
                        <div class="container ">
    
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    
</body>
{% endblock content %}

tajmoversapp/templates/service.html
{{form.media}}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Taj Movers Company</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    {% load static %}
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %} ">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %} ">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %} ">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %} ">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %} ">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %} ">
    <link rel="stylesheet" href="{% static 'css/animate.css' %} ">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %} ">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body >
    <header>
        <div class="header-area">
            <div id="sticky-header" class="main-header-area white-bg">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-2 col-lg-2">
                            <div class="logo-img">
                                <a href="{% url 'homepage' %} ">
                                    <!-- <img src="img/logo.png" alt=""> -->
                                    <h3 style="color: #ff5e13;">TAJ MOVERS</h3>
                                </a> 
                            </div>
                        </div>
                        <div class="col-xl-7 col-lg-7">
                            <div class="main-menu d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a class="active" href="{% url 'homepage' %} ">Home</a></li>
                                        <li><a href="{% url 'about' %} ">About</a></li>
                                        <li><a href="{% url 'service' %} ">Services</a></li>
                                        <li><a href="{% url 'contact' %} ">Contact</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3">
                            <div class="quote-area">
                                <div style="color:  #ff5e13;" class="Flaticon flaticon-right-arrow">                                    
                                </div>
                                <div class="get-quote d-none d-lg-block">
                                    <a class="boxed-btn" href="{% url 'contact' %} ">Get a quote</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                    <div class="search_input" id="search_input_box">
                        <div class="container ">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

        <!-- breadcrumb-start -->
        <section class="breadcrumb breadcrumb_bg banner-bg-1 overlay2 ptb200">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 offset-lg-1">
                        <div class="breadcrumb_iner">
                            <div class="breadcrumb_iner_item">
                                <h2>Our Services</h2>
                                <p> <a href="{% url 'homepage' %}">Home.</a> <span></span> Services</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- breadcrumb-end -->

    <!-- service-area-start -->
    <div class="service-area">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="section-title text-center mb-65">
                    <span>OUR SERVICES</span>
                    <h3>We provide all of your <br>
                        Moving solutions</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-4 col-md-4">
                    <div class="single-service">
                        <div class="service-thumb">
                            <img src="{% static 'img/service/3.jpg' %} " alt="">
                        </div>
                        <h3>Local, Timely Moves</h3>
                        <p>We consider your choice of time to move, Upon request. However, Late night demands may increase cost</p>
                        <!-- <a href="#" class="read-more">Read More</a> -->
                    </div>
                </div>
                <div class="col-xl-4 col-md-4">
                    <div class="single-service">
                        <div class="service-thumb">
                            <img src="{% static 'img/service/4.jpg' %} " alt="">
                        </div>
                        <h3>Office Moving </h3>
                        <p>We relieve you the stress of Packaging, moving and settling down in your new Office. Move Gracefully with us.</p>
                        <!-- <a href="#" class="read-more">Read More</a> -->
                    </div>
                </div>
                <div class="col-xl-4 col-md-4">
                    <div class="single-service">
                        <div class="service-thumb">
                            <img src="{% static 'img/service/1.jpg' %} " alt="">
                        </div>
                        <h3>Long Distance Moving</h3>
                        <p>We also cover long distance moving/vacating at a friendly cost. Get in touch to get a quote.</p>
                        <!-- <a href="#" class="read-more">Read More</a> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- service-area-end -->

    <!-- location-area-start -->
    <div class="addres-area black-bg section-padding">
        <div class="container">
            <div class="row">
                <div class="col-xl-4 col-md-4">
                    <div class="single-address text-center">
                        <div class="addres-icon">
                            <img src="{% static 'img/icon/1.png' %} " alt="">
                        </div>
                        <h3>Our Location</h3>
                        <p>Nairobi, Kenya<br>
                           <span class="underline-hover"> Mombasa Road</span></p>
                    </div>
                </div>
                <div class="col-xl-4 col-md-4">
                    <div class="single-address text-center">
                        <div class="addres-icon">
                            <img src="{% static 'img/icon/2.png' %} " alt="">
                        </div>
                        <h3>Opening hour</h3>
                        <p>Mon-Fri (9.00-19.00) <br>
                            Sat-Sun <span class="underline-hover">(Closed)</span></p>
                    </div>
                </div>
                <div class="col-xl-4 col-md-4">
                    <div class="single-address text-center">
                        <div class="addres-icon">
                            <img src="{% static 'img/icon/3.png' %} " alt="">
                        </div>
                        <h3>Drop a message</h3>
                        <p>
                            +254 70022 9711
                            <br>
                            <img width="20px" height="20px" src="{% static 'img/gmail.png' %} "> :<a style="text-decoration: none; color: #ff5e13;" href="mailto:japhethfriday@gmail.com?Subject=Hello%20again" target="_top"><span class="underline-hover">Mail Us </span></a>
                        </p> 
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- location-area-end -->

    <!-- footer-start -->
    <footer">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="copyright_part_text text-center">
                        <p class="footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer-end -->

    <!-- JS here -->
    <script rel="stylesheet/" src="{% static 'js/vendor/modernizr-3.5.0.min.js' %} "></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %} "></script>
    <script src="{% static 'js/popper.min.js' %} "></script>
    <script src="{% static 'js/bootstrap.min.js' %} "></script>
    <script src="{% static 'js/owl.carousel.min.js' %} "></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %} "></script>
    <script src="{% static 'js/ajax-form.js' %} "></script>
    <script src="{% static 'js/waypoints.min.js' %} "></script>
    <script src="{% static 'js/jquery.counterup.min.js' %} "></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %} "></script>
    <script src="{% static 'js/scrollIt.js' %} "></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %} "></script>
    <script src="{% static 'js/wow.min.js' %} "></script>
    <script src="{% static 'js/nice-select.min.js' %} "></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %} "></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' % } "></script>
    <script src="{% static 'js/plugins.js' %} "></script>

    <!--contact js-->
    <script src="{% static 'js/contact.js' %} "></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %} "></script>
    <script src="{% static 'js/jquery.form.js' %} "></script>
    <script src="{% static 'js/jquery.validate.min.js' %} "></script>
    <script src="{% static 'js/mail-script.js' %} "></script>
    <script src="{% static 'js/main.js' %} "></script>

</body>

</html>

tajmoversapp/templates/tajtemplates/base.html
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Taj Movers Company</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- <link rel="manifest" href="site.webmanifest"> -->
    {% load static %}
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png' %} ">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %} ">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %} ">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %} ">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %} ">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %} ">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %} ">
    <link rel="stylesheet" href="{% static 'css/animate.css' %} ">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %} ">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>
    
    {% include 'navbar.html' %}

    {% block content %}
    {% endblock %}
    
   

    <!-- JS here -->
    <script rel="stylesheet/" src="{% static 'js/vendor/modernizr-3.5.0.min.js' %} "></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %} "></script>
    <script src="{% static 'js/popper.min.js' %} "></script>
    <script src="{% static 'js/bootstrap.min.js' %} "></script>
    <script src="{% static 'js/owl.carousel.min.js' %} "></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %} "></script>
    <script src="{% static 'js/ajax-form.js' %} "></script>
    <script src="{% static 'js/waypoints.min.js' %} "></script>
    <script src="{% static 'js/jquery.counterup.min.js' %} "></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %} "></script>
    <script src="{% static 'js/scrollIt.js' %} "></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %} "></script>
    <script src="{% static 'js/wow.min.js' %} "></script>
    <script src="{% static 'js/nice-select.min.js' %} "></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %} "></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' % } "></script>
    <script src="{% static 'js/plugins.js' %} "></script>

    <!--contact js-->js/main.js
    <script src="{% static 'js/contact.js' %} "></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %} "></script>
    <script src="{% static 'js/jquery.form.js' %} "></script>
    <script src="{% static 'js/jquery.validate.min.js' %} "></script>
    <script src="{% static 'js/mail-script.js' %} "></script>
    <script src="{% static 'js/main.js' %} "></script>

</body>

</html>